sonar.projectKey=MindJunkies_mindjunkies
sonar.projectName=mindjunkies
sonar.projectVersion=1.0
sonar.organization=mindjunkies

# Source code settings
sonar.sources=./
sonar.exclusions=**/migrations/**/*, **/tests/**, **/static/**, **media/**

sonar.language=py
sonar.python.version=3.12

# Test and Coverage reports
sonar.python.coverage.reportPaths=coverage.xml
sonar.tests=courses/
sonar.test.inclusions=courses/tests.py
